Update 2 files
- /.gitlab-ci.yml
- /kubernetes/deployment.yaml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -30,10 +30,10 @@ stages:
   - build_update_manifest
   - push_manifest
   - argo_refresh
-  - tagging
-  - approve
-  - build_production
-  - push_production
+  # - tagging
+  # - approve
+  # - build_production
+  # - push_production
 
       
 ##################################### build_update_manifest #####################################
@@ -41,7 +41,7 @@ stages:
 .build:
   stage: build_update_manifest
   tags:
-    - runner2                    #Change_Me_Production  (change to runner1)
+    - runner1                    #Change_Me_Production  (change to runner1)
   variables:
     CONTAINER_PORT: "8000"        #Change_Me  (service port : 80 or 8000)
     REPLICAS: ""
@@ -116,7 +116,7 @@ update-staging:
 .push:
   stage: push_manifest
   tags:
-    - runner2                      #Change_Me_Production  (change to runner1)
+    - runner1                      #Change_Me_Production  (change to runner1)
   variables:
     BRANCH: ""
   script:
@@ -167,7 +167,7 @@ push-staging:
 .refresh:
   stage: argo_refresh
   tags:
-    - runner2                      
+    - runner1                      
   variables:
     ARGO_HOST: ""
     ARGO_USER: ""
@@ -180,194 +180,194 @@ push-staging:
   only:
     - main
 
-argo-refresh-staging:
-  extends: .refresh
-  variables:
-    ARGO_HOST: $argohost_stg
-    ARGO_USER: $argouser_stg
-    ARGO_PASS: $argopass_stg
-  
-# argo-refresh-production:
+# argo-refresh-staging:
 #   extends: .refresh
 #   variables:
-#     ARGO_HOST: $argohost
-#     ARGO_USER: $argouser
-#     ARGO_PASS: $argopass
+#     ARGO_HOST: $argohost_stg
+#     ARGO_USER: $argouser_stg
+#     ARGO_PASS: $argopass_stg
+  
+argo-refresh-production:
+  extends: .refresh
+  variables:
+    ARGO_HOST: $argohost
+    ARGO_USER: $argouser
+    ARGO_PASS: $argopass
 
 ############################################## tagging ################################################
 
-tagging:
-  stage: tagging
-  tags:
-    - runner2
-  when: manual
-  # variables:
-  #   GIT_STRATEGY: clone
-  environment:
-    name: production
-  before_script:
-    - |
-      if [[ ! " $ALLOWED_USERS " =~ " $GITLAB_USER_LOGIN " ]]; then
-        echo "❌ ERROR: User '$GITLAB_USER_LOGIN' is not authorized!"
-        echo "   Only system administrators or tech leads can deploy to production."
-        exit 1
-      fi
-  script:
-    - LATEST_TAG=$PREVIOUS_TAG
-    - MAJOR=$(echo $LATEST_TAG | cut -d. -f1 | tr -d 'v')
-    - MINOR=$(echo $LATEST_TAG | cut -d. -f2)
-    - PATCH=$(echo $LATEST_TAG | cut -d. -f3)
+# tagging:
+#   stage: tagging
+#   tags:
+#     - runner1
+#   when: manual
+#   # variables:
+#   #   GIT_STRATEGY: clone
+#   environment:
+#     name: production
+#   before_script:
+#     - |
+#       if [[ ! " $ALLOWED_USERS " =~ " $GITLAB_USER_LOGIN " ]]; then
+#         echo "❌ ERROR: User '$GITLAB_USER_LOGIN' is not authorized!"
+#         echo "   Only system administrators or tech leads can deploy to production."
+#         exit 1
+#       fi
+#   script:
+#     - LATEST_TAG=$PREVIOUS_TAG
+#     - MAJOR=$(echo $LATEST_TAG | cut -d. -f1 | tr -d 'v')
+#     - MINOR=$(echo $LATEST_TAG | cut -d. -f2)
+#     - PATCH=$(echo $LATEST_TAG | cut -d. -f3)
 
-    - |
-      echo "Current base tag is: $LATEST_TAG"
-      if [ "$tag" = "patch" ]; then
-        export NEW_TAG="v${MAJOR}.${MINOR}.$((PATCH+1))"
-      elif [ "$tag" = "minor" ]; then
-        export NEW_TAG="v${MAJOR}.$((MINOR+1)).0"
-      elif [ "$tag" = "major" ]; then
-        export NEW_TAG="v$((MAJOR+1)).0.0"
-      else
-        export NEW_TAG="v${MAJOR}.${MINOR}.$((PATCH+1))"
-        echo "❌ ERROR: Invalid or missing tag! (Value was: '$tag')"
-        echo "Please select 'patch', 'minor', or 'major' when running this manual job."
-        exit 1
-      fi
-      echo "New production tag will be: $NEW_TAG"
+#     - |
+#       echo "Current base tag is: $LATEST_TAG"
+#       if [ "$tag" = "patch" ]; then
+#         export NEW_TAG="v${MAJOR}.${MINOR}.$((PATCH+1))"
+#       elif [ "$tag" = "minor" ]; then
+#         export NEW_TAG="v${MAJOR}.$((MINOR+1)).0"
+#       elif [ "$tag" = "major" ]; then
+#         export NEW_TAG="v$((MAJOR+1)).0.0"
+#       else
+#         export NEW_TAG="v${MAJOR}.${MINOR}.$((PATCH+1))"
+#         echo "❌ ERROR: Invalid or missing tag! (Value was: '$tag')"
+#         echo "Please select 'patch', 'minor', or 'major' when running this manual job."
+#         exit 1
+#       fi
+#       echo "New production tag will be: $NEW_TAG"
 
-      git config --global user.email "runner@gmail.com"
-      git config --global user.name "shell-runner"
-      git remote set-url origin "http://oauth2:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
-      git tag $NEW_TAG
-      git push origin $NEW_TAG
-  only:
-    - main
+#       git config --global user.email "runner@gmail.com"
+#       git config --global user.name "shell-runner"
+#       git remote set-url origin "http://oauth2:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
+#       git tag $NEW_TAG
+#       git push origin $NEW_TAG
+#   only:
+#     - main
 
-############################################## approve ################################################
+# ############################################## approve ################################################
 
-.approve_production:
-  stage: approve
-  tags:
-    - runner2
-  when: manual
-  needs: ["tagging"]
-  environment:
-    name: production
-  variables:
-    STAGE_NAME: ""
-  before_script:
-    - |
-      if [[ ! " $ALLOWED_USERS " =~ " $GITLAB_USER_LOGIN " ]]; then
-        echo "❌ ERROR: User '$GITLAB_USER_LOGIN' is not authorized!"
-        echo "   Only system administrators or tech leads can approve and deploy to production."
-        exit 1
-      fi
-  script:
-    - echo "$STAGE_NAME Deploy Approved By $GITLAB_USER_LOGIN"
-  only:
-    - main
+# .approve_production:
+#   stage: approve
+#   tags:
+#     - runner1
+#   when: manual
+#   needs: ["tagging"]
+#   environment:
+#     name: production
+#   variables:
+#     STAGE_NAME: ""
+#   before_script:
+#     - |
+#       if [[ ! " $ALLOWED_USERS " =~ " $GITLAB_USER_LOGIN " ]]; then
+#         echo "❌ ERROR: User '$GITLAB_USER_LOGIN' is not authorized!"
+#         echo "   Only system administrators or tech leads can approve and deploy to production."
+#         exit 1
+#       fi
+#   script:
+#     - echo "$STAGE_NAME Deploy Approved By $GITLAB_USER_LOGIN"
+#   only:
+#     - main
 
-approve-sepah:
-  extends: .approve_production
-  variables:
-    STAGE_NAME: "sepah"
+# approve-sepah:
+#   extends: .approve_production
+#   variables:
+#     STAGE_NAME: "sepah"
   
-approve-bonyad:
-  extends: .approve_production
-  variables:
-    STAGE_NAME: "bonyad"
+# approve-bonyad:
+#   extends: .approve_production
+#   variables:
+#     STAGE_NAME: "bonyad"
 
-############################################ build production ##############################################
+# ############################################ build production ##############################################
 
-.build-prod:
-  stage: build_production
-  tags:
-    - runner2                    #Change_Me_Production  (change to runner1)
-  variables:
-    CONTAINER_PORT: "8000"        #Change_Me  (service port : 80 or 8000)
-    REPLICAS: "1"
-    # STAGE_NAME: ""
-  script:
-    # - export TARGET_IMAGE=$TARGET_REGISTRY/$TARGET_REGISTRY_PATH/microservice/$MICRO_SERVICE-$STAGE_NAME
-    - export TARGET_IMAGE=$TARGET_REGISTRY/$TARGET_REGISTRY_PATH/microservice/$MICRO_SERVICE
-    - export TARGET_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "$PREVIOUS_TAG")
-    - skopeo copy --src-tls-verify=false --src-creds "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" --dest-creds "$CI_REGISTRY_SEP_USER:$CI_REGISTRY_SEP_PASSWORD" docker://$PREVIOUS_IMAGE:$PREVIOUS_STAGE_TAG docker://$TARGET_IMAGE:$TARGET_TAG
-    - export IMAGE_NAME=$TARGET_IMAGE
-    - export IMAGE_TAG=$TARGET_TAG
-    - envsubst < kubernetes/deployment.yaml > deployment-$MICRO_SERVICE.yaml
+# .build-prod:
+#   stage: build_production
+#   tags:
+#     - runner1                    #Change_Me_Production  (change to runner1)
+#   variables:
+#     CONTAINER_PORT: "8000"        #Change_Me  (service port : 80 or 8000)
+#     REPLICAS: "1"
+#     # STAGE_NAME: ""
+#   script:
+#     # - export TARGET_IMAGE=$TARGET_REGISTRY/$TARGET_REGISTRY_PATH/microservice/$MICRO_SERVICE-$STAGE_NAME
+#     - export TARGET_IMAGE=$TARGET_REGISTRY/$TARGET_REGISTRY_PATH/microservice/$MICRO_SERVICE
+#     - export TARGET_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "$PREVIOUS_TAG")
+#     - skopeo copy --src-tls-verify=false --src-creds "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" --dest-creds "$CI_REGISTRY_SEP_USER:$CI_REGISTRY_SEP_PASSWORD" docker://$PREVIOUS_IMAGE:$PREVIOUS_STAGE_TAG docker://$TARGET_IMAGE:$TARGET_TAG
+#     - export IMAGE_NAME=$TARGET_IMAGE
+#     - export IMAGE_TAG=$TARGET_TAG
+#     - envsubst < kubernetes/deployment.yaml > deployment-$MICRO_SERVICE.yaml
 
-    # - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
-    # # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-    # - docker pull $PREVIOUS_IMAGE:$PREVIOUS_STAGE_TAG
-    # - docker logout
-    # - echo "$CI_REGISTRY_SEP_PASSWORD" | docker login -u $CI_REGISTRY_SEP_USER --password-stdin $TARGET_REGISTRY
-    # # - docker login -u $CI_REGISTRY_SEP_USER -p $CI_REGISTRY_SEP_PASSWORD $TARGET_REGISTRY
-    # - docker tag $PREVIOUS_IMAGE:$PREVIOUS_STAGE_TAG $TARGET_IMAGE:$TARGET_TAG
-    # - docker push $TARGET_IMAGE:$TARGET_TAG
-    # - docker logout $TARGET_REGISTRY
-  artifacts:
-    paths:
-      - deployment-$MICRO_SERVICE.yaml
-    expire_in: 1 hour
-  only:
-    - main
+#     # - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
+#     # # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+#     # - docker pull $PREVIOUS_IMAGE:$PREVIOUS_STAGE_TAG
+#     # - docker logout
+#     # - echo "$CI_REGISTRY_SEP_PASSWORD" | docker login -u $CI_REGISTRY_SEP_USER --password-stdin $TARGET_REGISTRY
+#     # # - docker login -u $CI_REGISTRY_SEP_USER -p $CI_REGISTRY_SEP_PASSWORD $TARGET_REGISTRY
+#     # - docker tag $PREVIOUS_IMAGE:$PREVIOUS_STAGE_TAG $TARGET_IMAGE:$TARGET_TAG
+#     # - docker push $TARGET_IMAGE:$TARGET_TAG
+#     # - docker logout $TARGET_REGISTRY
+#   artifacts:
+#     paths:
+#       - deployment-$MICRO_SERVICE.yaml
+#     expire_in: 1 hour
+#   only:
+#     - main
 
-build-sepah:
-  extends: .build-prod
-  needs:
-    - job: build-image
-      artifacts: true
-    - job: approve-sepah
+# build-sepah:
+#   extends: .build-prod
+#   needs:
+#     - job: build-image
+#       artifacts: true
+#     - job: approve-sepah
 
-build-bonyad:
-  extends: .build-prod
-  needs:
-    - job: build-image
-      artifacts: true
-    - job: approve-bonyad
+# build-bonyad:
+#   extends: .build-prod
+#   needs:
+#     - job: build-image
+#       artifacts: true
+#     - job: approve-bonyad
 
-############################################ push production ##############################################
+# ############################################ push production ##############################################
 
-.push-prod:
-  stage: push_production
-  tags:
-    - runner2                      #Change_Me_Production  (change to runner1)
-  variables:
-    BRANCH: ""
-  script:
-    - cd ..
-    - rm -rf $YAMLS_REPO
-    - git clone -b $BRANCH $REPOSITORY_YAML
-    - cd $YAMLS_REPO
-    - mv -t . ../$MONO_REPO/deployment*
-    - git config user.email "runner@gmail.com"
-    - git config user.name "shell-runner"
-    - git add .
-    - |
-      if ! git diff --cached --quiet; then
-        git commit -m "update yaml files"
+# .push-prod:
+#   stage: push_production
+#   tags:
+#     - runner1                      #Change_Me_Production  (change to runner1)
+#   variables:
+#     BRANCH: ""
+#   script:
+#     - cd ..
+#     - rm -rf $YAMLS_REPO
+#     - git clone -b $BRANCH $REPOSITORY_YAML
+#     - cd $YAMLS_REPO
+#     - mv -t . ../$MONO_REPO/deployment*
+#     - git config user.email "runner@gmail.com"
+#     - git config user.name "shell-runner"
+#     - git add .
+#     - |
+#       if ! git diff --cached --quiet; then
+#         git commit -m "update yaml files"
 
-        # push to main gitlab (origin)
-        git push origin "$BRANCH"
+#         # push to main gitlab (origin)
+#         git push origin "$BRANCH"
 
-        # push to target gitlab
-        git remote add target "$TARGET_REPO"
-        git push target "$BRANCH" --force
-      else
-        echo "No changes to commit"
-      fi
-    - cd ..
-    - rm -rf "$YAMLS_REPO"
-  only:
-    - main
+#         # push to target gitlab
+#         git remote add target "$TARGET_REPO"
+#         git push target "$BRANCH" --force
+#       else
+#         echo "No changes to commit"
+#       fi
+#     - cd ..
+#     - rm -rf "$YAMLS_REPO"
+#   only:
+#     - main
 
-push-sepah:
-  extends: .push-prod
-  variables:
-    BRANCH: "sepah"
-  needs: ["build-sepah"]
+# push-sepah:
+#   extends: .push-prod
+#   variables:
+#     BRANCH: "sepah"
+#   needs: ["build-sepah"]
   
-push-bonyad:
-  extends: .push-prod
-  variables:
-    BRANCH: "bonyad"
-  needs: ["build-bonyad"]
+# push-bonyad:
+#   extends: .push-prod
+#   variables:
+#     BRANCH: "bonyad"
+#   needs: ["build-bonyad"]
